export const IMAGES_GET_IMAGES_REQUEST = 'IMAGES_GET_IMAGES_REQUEST';
export const IMAGES_GET_IMAGES_SUCCESS = 'IMAGES_GET_IMAGES_SUCCESS';
export const IMAGES_GET_IMAGES_FAILURE = 'IMAGES_GET_IMAGES_FAILURE';